# Generated by Django 3.2.7 on 2021-09-15 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictures', '0004_auto_20210915_1730'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpicturerelation',
            unique_together={('user', 'picture')},
        ),
    ]
